import json

topic_associations = {
    "basketball": [
        "history of basketball",
        "Michael Jordan",
        "Los Angeles Lakers",
        "Baseball",
        "referees",
    ],
    "geography": [
        "history of geography",
        "world capitals",
        "rivers",
        "mountains",
        "continents",
    ],
    "music": [
        "instruments",
        "classical music",
        "rock and roll",
        "music theory",
        "concerts",
    ],
    "technology": [
        "artificial intelligence",
        "smartphones",
        "internet of things",
        "cybersecurity",
        "cloud computing",
    ],
    "cooking": ["recipes", "baking", "grilling", "culinary arts", "food safety"],
    "astronomy": ["planets", "stars", "galaxies", "black holes", "telescopes"],
    "literature": ["novels", "poetry", "drama", "authors", "literary analysis"],
    "mathematics": ["algebra", "geometry", "calculus", "statistics", "number theory"],
    "history": [
        "ancient civilizations",
        "world wars",
        "historical figures",
        "archaeology",
        "cultural history",
    ],
    "art": ["painting", "sculpture", "photography", "modern art", "art history"],
    "science": [
        "biology",
        "chemistry",
        "physics",
        "earth science",
        "environmental science",
    ],
    "economics": [
        "microeconomics",
        "macroeconomics",
        "international trade",
        "finance",
        "economic theory",
    ],
    "politics": [
        "political theory",
        "governments",
        "elections",
        "international relations",
        "political parties",
    ],
    "philosophy": ["ethics", "metaphysics", "epistemology", "logic", "existentialism"],
    "psychology": [
        "behavioral psychology",
        "cognitive psychology",
        "social psychology",
        "developmental psychology",
        "clinical psychology",
    ],
    "sports": ["soccer", "tennis", "golf", "swimming", "athletics"],
    "education": [
        "teaching methods",
        "curriculum development",
        "educational psychology",
        "special education",
        "e-learning",
    ],
    "health": ["nutrition", "exercise", "mental health", "public health", "diseases"],
    "travel": [
        "tourist destinations",
        "cultural tourism",
        "adventure travel",
        "travel planning",
        "travel safety",
    ],
    "environment": [
        "climate change",
        "sustainability",
        "conservation",
        "pollution",
        "renewable energy",
    ],
    "cinema": [
        "film genres",
        "directors",
        "film festivals",
        "cinematography",
        "screenwriting",
    ],
    "fashion": [
        "clothing design",
        "fashion trends",
        "fashion industry",
        "accessories",
        "beauty",
    ],
    "gardening": [
        "horticulture",
        "landscaping",
        "organic gardening",
        "plant care",
        "garden design",
    ],
    "law": [
        "criminal law",
        "civil law",
        "constitutional law",
        "international law",
        "legal theory",
    ],
    "architecture": [
        "building design",
        "architectural styles",
        "urban planning",
        "landscape architecture",
        "sustainable architecture",
    ],
    "engineering": [
        "mechanical engineering",
        "electrical engineering",
        "civil engineering",
        "chemical engineering",
        "aerospace engineering",
    ],
    "business": [
        "marketing",
        "management",
        "entrepreneurship",
        "accounting",
        "human resources",
    ],
    "religion": ["Christianity", "Islam", "Hinduism", "Buddhism", "Judaism"],
    "languages": ["English", "Spanish", "French", "Mandarin", "German"],
    "social media": ["Facebook", "Twitter", "Instagram", "LinkedIn", "YouTube"],
    "gaming": ["video games", "board games", "mobile games", "game design", "e-sports"],
    "fitness": [
        "strength training",
        "cardiovascular exercise",
        "yoga",
        "pilates",
        "nutrition",
    ],
    "medicine": [
        "anatomy",
        "pharmacology",
        "surgery",
        "medical research",
        "public health",
    ],
    "space": [
        "space exploration",
        "astronauts",
        "spacecraft",
        "space stations",
        "planetary science",
    ],
    "robotics": [
        "artificial intelligence",
        "machine learning",
        "robot design",
        "automation",
        "drones",
    ],
}

# Writing JSON data
with open("../topic_associations.json", "w") as f:
    json.dump(topic_associations, f, indent=4)
